<?php
$icons = array(
				"fas fa-bed", 
				"images/accommodation/icons/stove.jpg", 
				"fas fa-bath", 
				"", 
				"images/accommodation/icons/cctvicon.jpg", 
				"fas fa-fingerprint",
				"images/accommodation/icons/roomicon.jpg", 
				"fas fa-chess", 
				"fas fa-child", 
				"fa fa-wifi", 
				"fas fa-bus-alt", 
				"fas fa-tv", 
				"fas fa-dumbbell", 
				"fas fa-desktop", 
				"fas fa-television", 
				"fab fa-playstation", 
				"fas fa-shopping-cart", 
				"fas fa-wine-glass", 
				"", 
				"fas fa-bed", 
				"fas fa-futbol", 
				"fas fa-briefcase-medical", 
				"fab fa-accessible-icon", 
				"images/accommodation/icons/laundry.jpg", 
				"", 
				"images/accommodation/icons/electric.jpg", 
				"fas fa-parking", 
				"fas fa-futbol", 
				"fas fa-basketball-ball", 
				"fas fa-swimming-pool",				
				"");
?>